version: '3.9'

services:
  currency-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: currency_api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb?sslmode=disable  
      - REDIS_URL=redis://redis:6379 
    depends_on:
      - db  
      - redis  


  db:
    image: postgres:17 
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb  
      POSTGRES_USER: user  
      POSTGRES_PASSWORD: password  
    volumes:
      - db_data:/var/lib/postgresql/data 
    ports:
      - "5435:5432"


  redis:
    image: redis:latest  
    container_name: redis_db
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  


volumes:
  db_data:
  redis_data:
